{{- if and .Values.apiServer.ingress.enabled .Values.apiServer.ingress.domain -}}
{{- $fullName := include "explorer.fullname" . -}}
{{- $domain := .Values.apiServer.ingress.domain -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
  {{- with .Values.apiServer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 5000
{{- end }}
