apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spacemesh-api.fullname" . }}
  labels:
    {{- include "spacemesh-api.labels" . | nindent 4 }}
data:
  config.json: |
{{ required "configFile must be specified" .Values.configFile | .Files.Get | indent 4 }}
