apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.fullname" . }}-mongo
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  ports:
    - name: mongo
      port: 27017
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
    component: collector
